name = "KMLTracks"
uuid = "4ff081ab-3ccd-427e-9edf-9f84f91777da"
authors = ["SÃ©bastien Celles <s.celles@gmail.com>"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"

[compat]
TimeZones = ">= 0.10.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
